trigPositionStyle: Mouse
trigger:
  maxEffectTimes: 0
  shape:
    type: Circle
    radius: 0
  tagEnum: 0
  delay: 0
  trigPeriod: 0
  damage: 0
  ampFactor: 0
  damageTextColor: &o0
    r: 0
    g: 0
    b: 0
    a: 0
    grayscale: 0
    linear: *o0
    gamma: *o0
    maxColorComponent: 0
  damageTextPrefabName: 
  trigEffectName: 
  trigAudioName: 
  hitEffectName: 
  hitAudioName: 
  createEffectName: 
  createAudioName: 
  tag: 
slotNum: 0
