trigPositionStyle: Self
trigger:
  maxEffectTimes: 99
  trigStyle: Once
  shape:
    type: Circle
    radius: 1
  damage: 10
  ampFactor: 1
  damageTextColor:
    r: 1
    g: 1
    b: 1
    a: 1
  damageTextPrefabName: Prefabs/UI/FloatText
  trigEffectName: 
  trigAudioName: 
  hitEffectName: 
  hitAudioName: 
  createEffectName: Prefabs/Effect/Hit/SectorSlash.prefab
  createAudioName: Wave1.wav
  tag: HasDamage
slotNum: 2
